version: "3.9"

services:
  bets-db:
    image: postgres:14
    container_name: bsw-bets-db
    restart: always
    env_file:
      - configs/db.env
    networks:
      - bsw-test
    volumes:
      - ./volumes/pg_data_bets:/var/lib/postgresql/data

  events-db:
    image: postgres:14
    container_name: bsw-events-db
    restart: always
    env_file:
      - configs/db.env
    networks:
      - bsw-test
    volumes:
      - ./volumes/pg_data_events:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bsw-pgadmin
    restart: always
    env_file:
      - configs/pgadmin.env
    networks:
      - bsw-test
    depends_on:
      - bets-db
      - events-db
    ports:
      - 8003:80

  redis:
    image: redis:alpine
    container_name: bsw-redis
    restart: always
    networks:
      - bsw-test
    volumes:
      - ./volumes/redis_data:/data

  redis-gui:
    image: redislabs/redisinsight:latest
    container_name: bsw-redis-gui
    restart: always
    networks:
      - bsw-test
    depends_on:
      - redis
    ports:
      - 8002:8001

  line-provider:
    image: bsw-line-provider
    container_name: bsw-line-provider
    build:
      context: .
      dockerfile: dockerfiles/line-provider.dockerfile
    restart: always
    tty: true
    env_file:
      - ./configs/line-provider.env
    networks:
      - bsw-test
    volumes:
      - ./volumes/logs:/line-provider/logs
    depends_on:
      - events-db
      - redis
    ports:
      - 8001:81
    command: uvicorn run:app --host 0.0.0.0 --port 81


  bet-maker:
    image: bsw-bet-maker
    container_name: bsw-bet-maker
    build:
      context: .
      dockerfile: dockerfiles/bet-maker.dockerfile
    restart: always
    tty: true
    env_file:
      - ./configs/bet-maker.env
    networks:
      - bsw-test
    volumes:
      - ./volumes/logs:/bet-maker/logs
    depends_on:
      - bets-db
      - redis
      - line-provider

    ports:
      - 8000:80
    command: uvicorn run:app --host 0.0.0.0 --port 80

networks:
    bsw-test:
        external: true
